services:
  postgres:
    image: postgres:15-alpine
    container_name: clusters-db
    restart: always
    environment:
      POSTGRES_USER: clusters
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: clusters_control_plane
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: clusters-queue
    restart: always
    ports:
      - "6385:6379"

volumes:
  postgres_data:
